name: publish-main

on:
  push:
    branches: [ main ]

jobs:
  build:

    name: publish-release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 8.0.100
        # Authenticates packages to push to GPR
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'
    
    - name: Install dependencies
      run: dotnet restore
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}
        
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Pack
      run: dotnet pack --no-build --configuration Release /p:ContinuousIntegrationBuild=true -p:PackageID=Valdars.BlazorMarkdownEditor
      
    - name: PushGithub
      run: dotnet nuget push **/*.nupkg --no-symbols --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}
